# config/packages/security.yaml
security:
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/recette, roles: [ROLE_USER, ROLE_ADMIN] }

    providers:
        mon_login:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            security: true
            pattern: ^/
            anonymous: ~
            provider: mon_login
            form_login:
                login_path: login
                check_path: login
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                # 16.-----Login: suite du pt16 commencé ds Src/Login/SuccessHandler.php----
                success_handler: App\Login\SuccessHandler 
                # 16.------Suite dans Src/Login/SuccessHandler.php ----------------------------------------
            logout:
                path:   logout
                target: login
            # 17.--2/3------AJOUTER UNE LIGNE DE PARAMETRE DANS security.yaml  : access_denied_handler: App\Login\SuccessHandler...------
            access_denied_handler: App\Login\SuccessHandler
            # 17.------Suite dans Src/Login/SuccessHandler.php  : ajouter les Use---------------------------
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    encoders:
        App\Entity\User:
            algorithm: bcrypt
